### ISSUE TITLE
What is it CRC?

### ISSUE THREAD

**Issue by ArtKuz** [luckxiang/cordova-plugin-serial-port#1]
Hello.

In your example have CRC. What is it? How to look file `./crc/index.ts`?

```ts
import  { CRC } from './crc';
```

**Comment by luckxiang** [comment]
Sorry，As China is now celebrating the Spring Festival, I will reply to you in a few days.

**Comment by luckxiang** [comment]
CRC is Cyclic redundancy check, you can know more in [wiki](https://en.wikipedia.org/wiki/Cyclic_redundancy_check), and I add the crc.js code to the README.md.
I hope it can help you.

**Comment by ArtKuz** [comment]
Thank you.
