### ISSUE TITLE
OpenDevice give undefined result

### ISSUE THREAD

**Issue by devism** [luckxiang/cordova-plugin-serial-port#11]
The following code should work but it returns undefined for result. what would be a compatible es5 function since the example is uing es6 arrow functions?
cordova.plugins.SerialPortPlugin.openDevice([{dev:'/dev/ttyS8',baudrate:9600, flags:0, isHex:false}],
            (function (result) {
                return alert("result");
            })(),
            (function (error) {
                return alert("error");
            })()
            );

**Comment by luckxiang** [comment]
Sorry, have you solved this problem?
