### ISSUE TITLE
大佬，刚好我这边也是要弄串口对接其他机器来采集数据，可是我对硬件那边 的流程一脸懵逼，可以请教下吗

### ISSUE THREAD

**Issue by qikong333** [luckxiang/cordova-plugin-serial-port#6]

**Comment by luckxiang** [comment]
基于cordova|ionic吗?你有什么问题直接写在这里吧,串口本身是比较简单的,最重要是的和设备约定好数据传输的协议.对你来说:
- 第一步让设备开发人员提供串口发送的数据格式(协议)和调试设备,
- 第二步找个串口工具根据你们定义好的格式模拟一下串口收发,这里你不懂的话可以让设备开发者帮忙一下.这一步主要是帮助你对串口有个感性的认识.熟悉串口配置,顺便检查一下设备异常.
- 第三步在你的平台上找到串口收发数据的操作方式.配置串口,实现你们第一步定义好的协议.

**Comment by qikong333** [comment]
> 基于科尔多瓦|离子吗你有什么问题直接写在这里吧，串口本身是比较简单的，最重要是的和设备约定好数据传输的协议对你来说？：
> 
> * 第一步让设备开发人员提供串口发送的数据格式（协议）和调试设备，
> * 第二步找个串口工具根据你们定义好的格式模拟一下串口收发，这里你不懂的话可以让设备开发者帮忙一下。这一步主要是帮助你对串口有个感性的认识。熟悉串口配置，顺便检查一下设备异常。
> * 第三步在你的平台上找到串口收发数据的操作方式。配置串口，实现你们第一步定义好的协议。

兄弟，我也是做同样的东西，请问可以交流下吗

**Comment by qikong333** [comment]
弟，我也是做同样的东西，请问可以交流下吗

**Comment by qikong333** [comment]
兄弟，我也是做同样的东西，请问可以交流下吗

**Comment by luckxiang** [comment]
你qq发我邮箱吧,我加你

**Comment by qikong333** [comment]
1513372833
 谢谢



------------------ 原始邮件 ------------------
发件人: "时雨君"<notifications@github.com>; 
发送时间: 2019年5月22日(星期三) 中午12:49
收件人: "luckxiang/cordova-plugin-serial-port"<cordova-plugin-serial-port@noreply.github.com>; 
抄送: "1513372833"<1513372833@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [luckxiang/cordova-plugin-serial-port] 大佬，刚好我这边也是要弄串口对接其他机器来采集数据，可是我对硬件那边 的流程一脸懵逼，可以请教下吗 (#6)




你qq发我邮箱吧,我加你

**Comment by qikong333** [comment]
1513372833





------------------ 原始邮件 ------------------
发件人: "时雨君"<notifications@github.com>;
发送时间: 2019年5月22日(星期三) 中午12:49
收件人: "luckxiang/cordova-plugin-serial-port"<cordova-plugin-serial-port@noreply.github.com>;
抄送: "1513372833"<1513372833@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [luckxiang/cordova-plugin-serial-port] 大佬，刚好我这边也是要弄串口对接其他机器来采集数据，可是我对硬件那边 的流程一脸懵逼，可以请教下吗 (#6)




你qq发我邮箱吧,我加你
