### ISSUE TITLE
插件很棒，请教下读取的问题

### ISSUE THREAD

**Issue by gulullu** [luckxiang/cordova-plugin-serial-port#8]
读取是要通过定时器来一直读取吗还是有长连接？

谢谢。

**Comment by luckxiang** [comment]
1. 这个只是一个基本的读写API,java层有一个读取线程，如果数据没有及时被读走，会存在缓冲buff中，调用read接口的时候会把整个缓冲buff的数据都读上去。因此需要应用上开一个定时器去取数据。
2. 此外，只要你open了设备没有关闭，数据通路就会一直处于联通状态，这个应该就是你所说的长连接（串口通信没有长连接的概念）

**Comment by gulullu** [comment]
> 1. 这个只是一个基本的读写API,java层有一个读取线程，如果数据没有及时被读走，会存在缓冲buff中，调用read接口的时候会把整个缓冲buff的数据都读上去。因此需要应用上开一个定时器去取数据。
> 2. 此外，只要你open了设备没有关闭，数据通路就会一直处于联通状态，这个应该就是你所说的长连接（串口通信没有长连接的概念）

请问有没有遇到读取到的数据不完整的问题呢？

发送的数据是这样的，读取正常如下：

`读取到的内容:!A-A!{"oId":"000001212009061550481231","orderRemark":"","guideSn":"1","businessType":"ORDER_PAY","requestId":"000001211550571761","chanelStoreId":"001","amount":"0.01","goodsTag":"","memberMobile":"","benfitDetail":[{"goodsName":"男士风衣裤黑色","quantity":"1","goodsId":"010003","price":"1"}],"memberCardNo":"","password":"","excludeAmount":"0.00"}!A-A!`

但是偶尔会数据丢失：

` 读取到的内容:ile":"","benfitDetail":[{"goodsName":"男士风衣裤黑色","quantity":"1","goodsId":"010003","price":"1"}],"memberCardNo":"","password":"","excludeAmount":"0.00"}!A-A!!A-A!{"oId":"000001212009061550481231","orderRemark":"","guideSn":"1","businessType":"ORDER_PAY","requestId":"000001211550571761","chanelStoreId":"001","amount":"0.01","goodsTag":"","memberMobile":"","benfitDetail":[{"goodsName":"男士风衣裤黑色","quantity":"1","goodsId":"010003","price":"1"}],"memberCardNo":"","password":"","excludeAmount":"0.00"}!A-A!`

有没有什么方法解决呢？

**Comment by luckxiang** [comment]
如我在readme中所说，这个只是一个数据传输通路，你需要一套数据传输协议来保证数据的完整性和可靠性。此外，你这个看上去只是数据读取问题吧，数据发太快读取太慢导致发生了数据粘连

**Comment by luckxiang** [comment]
我先把问题关闭了哟，需要再打开
