### ISSUE TITLE
can't Cut Paper

### ISSUE THREAD

**Issue by kassari** [luckxiang/cordova-plugin-serial-port#9]
Hello,
i am able to print width this plugin but i still can't cut paper.

cordova.plugins.SerialPortPlugin.setHex(true);

      cordova.plugins.SerialPortPlugin.write('0x1D',
  res=> {
        console.log(res);
        //alert(res);
  },
  error=> {
      alert(error);
  });

      cordova.plugins.SerialPortPlugin.write('0x56',
  res=> {
        console.log(res);
        //alert(res);
  },
  error=> {
      alert(error);
  });

Can you help please

**Comment by luckxiang** [comment]
Do you use it on a serial printer ？ please make sure your instructions are working properly.
